### ISSUE TITLE
Calf Shields on Legs crashes game when jumping

### ISSUE THREAD

**Issue by shaggy1395** [TGMP/ModularArmour#17]
I added the Calf Shields to the legs, then put on the legs with no other armor.  I jumped once and the game crashed to desktop with the following log: http://pastebin.com/vdnbRmeD

The only other mod referenced is Galacticraft, so there may be some form of incompatibility.

As a side note, I was confused when trying to add mods to the various armor pieces.  Some upgrades say "does work" or "does not work", seemingly at random per armor piece.  For example, the calf shields said "does not work" for Legs and Boots, but showed "does work" for Chest.  On relaunching the game after the crash, it now shows "does work" for all 4 armor pieces.

**Comment by chbachman** [comment]
First, thanks for your support. It is always nice to see somebody that is using the mod, and post issues he finds. 

Second, I have some idea what is going on there. I can definitely fix the bug, however I am unsure how it happened.

**Comment by chbachman** [comment]
Closed due to time, and the side note has been implemented.
