### ISSUE TITLE
Holding Ctrl to show upgrades shows a blank "Unnamed" tooltip

### ISSUE THREAD

**Issue by shaggy1395** [TGMP/ModularArmour#18]
Screenshot below.  I can almost guarantee mod incompatibility, but without errors I wouldn't know how to determine which mod is affecting it.  Let me know if more info is needed.

![javaw 2015-01-04 02-59-52-88](https://cloud.githubusercontent.com/assets/9969370/5605394/075a0f16-93be-11e4-9be1-9f889b081bf8.jpg)

**Comment by chbachman** [comment]
I am going to push out a new version, hopefully today, that includes a "debug" feature. Can you update to that when I push that?

Also, is it the same modlist as your other crash?

**Comment by chbachman** [comment]
Okay, I have no idea what is causing this. If it comes up again, I'll reopen.
