### ISSUE TITLE
Crash when equipping leggins - internal server error

### ISSUE THREAD

**Issue by ruyanve** [TGMP/ModularArmour#26]
I probably did something wrong! :P
Added undead protection, walk speed, 2 energy upgrades and unblockable prot. to leggins, put them on and got kicked from the server.
Looks like the speed upgrade is the issue here. I have another speed boost from a Botania ring, if that is any help to you finding the problem...
Love the mod so far, hope I can put it back on the server soon! If you need any more information please let me know.

Here's the log: http://pastebin.com/KSGrkedL

Cheers!

**Comment by LiamHammett** [comment]
Seconding this as an issue.
