### ISSUE TITLE
Energy level of leggins - perma drain, reset by unequipping

### ISSUE THREAD

**Issue by ruyanve** [TGMP/ModularArmour#28]
Speed upgrade seems still to be an issue.

I don't know if this is intentional, if so I request considering a change in behavior: Even when standing still the speed upgrade drains energy. I'd much rather have them drain energy only when moving.

As it seems to be related I won't open a seperate issue for this: The energy level of leggins with walk speed upgrade resets to full when unequipping.

**Comment by chbachman** [comment]
Fixed in latest commit.
