### ISSUE TITLE
Request - Ender IO integration

### ISSUE THREAD

**Issue by ruyanve** [TGMP/ModularArmour#29]
While EnderIO has it's own version of a modular armour, I would love to see some sort of recipie alteration when EnderIO is detected. The upgrades are way to cheap in their vanilla form for a modded setup with EnderIO instead of TE.

**Comment by ruyanve** [comment]
In addition, the recharging times in EnderIO capacitors (the creative kind even) are way too long. Is the max energy input of MA limited in some way?

**Comment by chbachman** [comment]
The input is limited. That I am going to increase in the next version. In Modular Armour 2.0, this will be configurable.

The recipes are a pain to make, so I'll wait on that.
