### ISSUE TITLE
Discussion - MPS like block for upgrades instead of per item right click behaviour?

### ISSUE THREAD

**Issue by ruyanve** [TGMP/ModularArmour#30]
While testing today it became sort of tedious to put upgrades on items. I would much rather have a block like MPS has to easily put upgrades on a number of items quickly.
Due to the number of upgrades (which is a good thing) I had to look up recipies all the time and that just was not fun.
I know this may be considered not to be original but who gives a shit about that anyway if it works better?

**Comment by ruyanve** [comment]
I thought about it a bit and came up with a more original idea. No idea how this may work code wise tho...
How about a modular chamber? You step in, it detects any armour pieces and opens a GUI where you can upgrade everything.
Think iron man -esque...

**Comment by chbachman** [comment]
I had a better idea for this. I would implement a upgrade button in the recipe gui. If you have all the items in your inventory, then you can click it and it removes it from your inventory, and adds the upgrades.

**Comment by ruyanve** [comment]
Good idea!
