### ISSUE TITLE
Unblockable Protection upgrade - what does it protect against?

### ISSUE THREAD

**Issue by ruyanve** [TGMP/ModularArmour#31]
The ingame documentation is a bit too vague ... I play MC since it's alpha days and have no idea what would be condidered unblockable.
Due to the amount of diamonds invested I would like to see some sort of regular armour protection to be shown when having this upgrade. The specific protection upgrades would be an addition like enchantments are on regular armour.
I tested with a full set of unblockable upgrades and still was a three hit for a zombie. Didn't seem right balance wise.

**Comment by chbachman** [comment]
The unblockable upgrade protects against "unblockable" damage, such as a Ti-Con Rapier, Flux Damage, or many other sources of "armour-piercing" damage. It also only protects 10% from them.

**Comment by chbachman** [comment]
Make a PR, and I'll add it.
