### ISSUE TITLE
Auto die if you've been flying long

### ISSUE THREAD

**Issue by GonzaloXavier** [TGMP/ModularArmour#33]
By having the jetpack upgrade and not the long fall upgrade you can land the most delicate way possible but you accumulate fall damage over time so if you touch the ground you die. The same phenomenon happens when you attach an entity to a leash and start flying with it, the entity over time accumulates fall damage and if it even kisses the ground it dies. 

PS: What are the Calf Shields for? I seem to notice no difference.

**Comment by chbachman** [comment]
What version of the mod is this? Can you use the version located here: http://tehnut.info/jenkins/view/chbachman/job/ModularArmour/lastSuccessfulBuild/?

**Comment by chbachman** [comment]
@eruantien-hiraear Can you test this?

**Comment by eruantien-hiraear** [comment]
On it, sorry for the delay guv'ner.

**Comment by eruantien-hiraear** [comment]
Confirmed, using version "ModularArmour-1.7.10-0.0.10-6.jar". Long fall boots make no difference to the damage taken, while the calf shields seem to help, but only very slightly (1-2 HP).

**Comment by eruantien-hiraear** [comment]
Paging @chbachman ...

**Comment by chbachman** [comment]
The calf shields are now working as well.
So don't forget to wear them.
