### ISSUE TITLE
Server crashes from Jump boost upgrade

### ISSUE THREAD

**Issue by FakoTheGreat** [TGMP/ModularArmour#40]
As title says, build 12 crashes servers running it when a player with the Jump Upgrade in their armor attempts to jump.  Crash log is here: http://pastebin.com/yHJg5BJ0, and by checking the line mentioned you find this: https://github.com/TGMP/ModularArmour/blob/master/src/main/java/chbachman/armour/upgrade/upgradeList/UpgradeJumpBoost.java#L45

It'll crash on the server as the server doesn't know about the keyboard.  I've been told you can check for Sneaking instead of Left Shift, as that is shared between both sides.

**Comment by chbachman** [comment]
Fixed in newest version.
