### ISSUE TITLE
Food upgrade 

### ISSUE THREAD

**Issue by Keridos** [TGMP/ModularArmour#49]
The food upgrade seems to eat all food items it gets. Maybe make it have an internal buffer and stop eating more food when its full?

**Comment by chbachman** [comment]
It should have a internal buffer once it is full. It stops in dev. How much food are you giving it?

**Comment by Keridos** [comment]
It ate about 4 or 5 stacks of steak. For a friend of mine it ate about 5 stacks of bread before stopping. for me it never stopped.
