### ISSUE TITLE
Crash to desktop while loading single player world

### ISSUE THREAD

**Issue by Thistlebalm** [TGMP/ModularArmour#52]
I was putting together a single player modpack. When loading into a world I'd get "a fatal error has occurred this connection is terminated" and then get kicked to the multiplayer server screen. After I started removing other mods to narrow it down I began getting the complete client crashes. 

Here's the crash log for the client crash: http://pastebin.com/raw.php?i=c9xudgXH

I didn't save the logs for the kicks to multiplayer screens, those were giving some error about io.netty I believe.

**Comment by chbachman** [comment]
Remove Random Mobs

**Comment by Thistlebalm** [comment]
Is that a mod? I don't have it installed. I fixed the crash by removing modular armor.

**Comment by chbachman** [comment]
You have optifine installed. Try removing it and adding in modular armour. 




If that doesn't work, I'll take a deeper look into it. I don't see anything in there that points to my code being the problem. 




If it persists there are a few things I can try, though.

**Comment by Thistlebalm** [comment]
Alright, I removed optifine and now it did the kick back to multiplayer server screen, twice. I first tried loading a old world, then I made a new world.
Here's the console log from building the new world to the 'crash': http://pastebin.com/raw.php?i=yp8rUvFT

I looked around for the RandomMobs.entityLoaded issue, but didn't see anything concrete. I'll start looking into the Netty IO stuff now.

**Comment by Thistlebalm** [comment]
I removed modular armor and made a new world to compare the logs. I noticed thermal expansion never did "[17:50:11] [Client thread/INFO] [ThermalExpansion]: Receiving Server Configuration..." in the crash log.
Don't know if it means anything, just trying to help.

**Comment by chbachman** [comment]
Ok, try the newest build. It might fix the problem.

**Comment by McyD** [comment]
Same issue here using latest .  Not using random mobs or Optifine.  When creating world crashes with fatal error and end up at Server screen.

**Comment by chbachman** [comment]
I accidentally didn't push the newest build. Try with the newest build as of ~5 Seconds ago.

**Comment by McyD** [comment]
ah, k

**Comment by chbachman** [comment]
Build here if you need it: http://tehnut.info/jenkins/job/ModularArmour/

**Comment by McyD** [comment]
Loading it now, should know in a few minutes

**Comment by McyD** [comment]
Error still occuring

**Comment by Thistlebalm** [comment]
Still getting the error as well. 
Here's the errory bits: http://pastebin.com/raw.php?i=ArxBRvej

**Comment by chbachman** [comment]
Ok, I think I figured it out. 

It probably wasn't a good idea to be hijacking all of CoFH's Packets. 

I changed it to have a separate channel, and that might have been causing it. 

The new build is coming soon.

**Comment by Thistlebalm** [comment]
Looks good here. Tested on an old world and genned a new world with no problems. :+1:

**Comment by McyD** [comment]
Second that, loads fine now.  Thanks for the quick fix.

**Comment by chbachman** [comment]
As soon as I saw it, I realized that I was doing something terribly wrong. 

Remember, any bugs you have, report here.
