### ISSUE TITLE
Piston metadata issue

### ISSUE THREAD

**Issue by radioactivated** [TGMP/ModularArmour#53]
(MC version 1.7.10, heavily modded)
The metadata value for the pistons used in Jump Boost and similar upgrades seems to be :32767, which doesn't match the normal piston value. As a result, these upgrades can't be crafted normally.

![ss 2015-06-21 at 06 19 10](https://cloud.githubusercontent.com/assets/3967418/8273580/40c68cd0-1842-11e5-9c2b-6bac49ece119.jpg)
![ss 2015-06-21 at 06 20 07](https://cloud.githubusercontent.com/assets/3967418/8273581/40c6e7b6-1842-11e5-8949-006e72a410f6.jpg)

**Comment by chbachman** [comment]
Can you show me the files in config/modulararmour/recipes? 

What do the broken recipes have as thier JSON recipes?

**Comment by radioactivated** [comment]
The json recipe in the config seems to list pistons with metadata 32767 (at least for the jump boost). (I'm assuming this is meant to be configurable, in which case I'll speak with the server admins.)

![ss 2015-06-23 at 02 33 18](https://cloud.githubusercontent.com/assets/3967418/8314051/eceffa6e-19b4-11e5-8866-b04cc4b802d2.png)

**Comment by chbachman** [comment]
Yeah, if the server admins have it wrong it  might have caused that. However, they might also have generated wrong. I'll try to reproduce and see if I can get them to generate incorrectly.

**Comment by chbachman** [comment]
If it generated, feel free to comment on it again.
