### ISSUE TITLE
Can't add upgrade or see recipes

### ISSUE THREAD

**Issue by logut** [TGMP/ModularArmour#54]
I'm using a private modpack and i want to add Modular Armour but when i put a recipe in the "upgrade table" it recognize the recipe but clicking on the add upgrade button don't do anything .. as clicking on recipies button or remove items button .. mod list : http://pastebin.com/XUJgtPxd
![modular_armour](https://cloud.githubusercontent.com/assets/6680221/8286837/3b29c0c4-190c-11e5-9a5a-0d1485e6d478.PNG)
PS : i had the same issue as https://github.com/TGMP/ModularArmour/issues/52 with version 1.0.7-30

**Comment by chbachman** [comment]
Thanks for reporting. 

I already found this and am completely stumped by it. 




I'll work on it now.

**Comment by chbachman** [comment]
Can you test with the latest build?
I think I fixed it.

**Comment by logut** [comment]
yeah ! it works ! thanks you for your work ;)

**Comment by chbachman** [comment]
Thanks for reporting!
