### ISSUE TITLE
General Protection Upgrade

### ISSUE THREAD

**Issue by Delerium** [TGMP/ModularArmour#55]
The armor lists protection values in it's description, but actually provides no armor protection against attacks, and does not increase the armor bar above the hearts in the UI.

**Comment by chbachman** [comment]
Come on github, I only mentioned it, not closed it.

**Comment by Delerium** [comment]
tested the new version, still not working.  Very fast fix response though. props!

**Comment by chbachman** [comment]
Are you increasing the percentage under the config tab? 




It defaults to 0% protection.

**Comment by radioactivated** [comment]
I think that the armor needs to have some of the protection upgrades to really be effective against damage.

**Comment by Delerium** [comment]
I'm playing it native on Horizons: Daybreaker.  I checked the config, and it lists values for each damage type modifier, but nothing listed for base "protection" which every armor should have, as not all mobs will fit into these "damage type" categories.  There are no upgrades for "base armor rating", and without any base protection the armor is rather useless.  I'd be happy with upgrades that provide different levels of base protection, that would be cool.

**Comment by chbachman** [comment]
Am I correct with my changes to the question?

**Comment by Delerium** [comment]
Yeah that looks about right.  Right now I've been swapping armor sets between my combat set and this one for utility.  Would be great to just use one set.

**Comment by Delerium** [comment]
This is of course your choice, but since you are trying to keep things unconventional and wanted something unique, perhaps this could be split into "Melee protection" and "Projectile Protection" instead of one "general protection".  I'm just trying to figure out a modular way of getting protection against those edge cases that don't have an upgrade for it, like melee or ranged attacks from creatures that aren't undead or arachnid (no protection listed for that type.)

**Comment by chbachman** [comment]
Ok, added in the most recent version.
