### ISSUE TITLE
walking speed and jump boost sliders are linked

### ISSUE THREAD

**Issue by Delerium** [TGMP/ModularArmour#56]
If you have both walking speed boost and jump boost on your leg armor and you adjust the slider for either one, the other one gets changed as well.  In addition, jump boost seems locked at maximum and doesn't adjust with the slider at all.

**Comment by chbachman** [comment]
Probably have both of the identifiers as the same thing. 

I'll take a look.

**Comment by Delerium** [comment]
I just tested it, it seems it's every slider on a piece of armor, not just those two skills.

**Comment by chbachman** [comment]
The sliders are no longer linked, so I'm closing this.
