### ISSUE TITLE
Armour Camoflage Upgrade Recipe doesn't work.

### ISSUE THREAD

**Issue by TennePG** [TGMP/ModularArmour#57]
While both of the armor textures look rather nice, I was wondering if it would be possible if an upgrade could be added that removes/hides the armor texture? 

Also, another suggestion, would it also be possible for the armor to be masked as another type of armor?(example, masking it as iron armor, gold armor, Thaumcraft Fortress armor,  etc).

**Comment by chbachman** [comment]
There is one, look for the armour camouflage upgrade. 




The masking is a possibility. I'll take a look.

**Comment by TennePG** [comment]
Ah okay, whenever I see armor camouflage, I always think of invisibility. I guess I better start re-thinking on that.

**Comment by TennePG** [comment]
The camouflage upgrade doesn't work. I tried it with all four variations of the invisibility potion(Standard, extended, standard splash, extended splash).

**Comment by chbachman** [comment]
Changed potion recipe to one involving glass.
