### ISSUE TITLE
Internal Server Error when Adding Upgrade 1.0.12-35

### ISSUE THREAD

**Issue by TechnoColt** [TGMP/ModularArmour#61]
Hello. When I am in the upgrade menu and I click on "Add Upgrade?" I am booted from the server for an internal server error. When I log back on, the items are missing from my inventory, but no upgrade is applied. Additionally, but not caused by the previous bug, the mod will no longer let me put items into the upgrade inventory. It just says "No Upgrade Selected Yet!" Is there something I am doing wrong as far as that goes?

To clarify: The error happens when I click "Add Upgrade?" from the recipe view.

**Comment by chbachman** [comment]
Two things. 

One, can you update to the latest version of Modular Armour? 

Two, can you replicate it in the newest version, and when you do, pastebin the log for me?

Thanks

**Comment by chbachman** [comment]
Reopen if able to reproduce in latest version.
