### ISSUE TITLE
Upgrade Sliders Overlapping

### ISSUE THREAD

**Issue by ChromeFlux** [TGMP/ModularArmour#63]
At first i thought it was just the legs then i realized every armour piece's sliders (haven't tested the rings and such) are setting themselves to the same value. So if i want a speed boost of 15% and a jump boost of 100%, as soon as i close out of the window and put them on then take them off and open it again it'll both be at 100% or both be at 15%. depending on which upgrade is applied first i think, also, the sliders arent able to be moved by clicking, instead you have to move the scrollwheel. I think this should be changed to be able to be used by clicking and dragging.

**Comment by chbachman** [comment]
All fixed in the newest version.

**Comment by ChromeFlux** [comment]
Ok. Sorry, i didnt think about if im playing on an outdated version.

**Comment by chbachman** [comment]
The newest version isn't released yet, I haven't had the time recently.

**Comment by ChromeFlux** [comment]
That's fine. Just don't overwork yourself
:)

**Comment by chbachman** [comment]
Just pushed a new version, should fix it.
