### ISSUE TITLE
Invisibility not able to be put in as an upgrade

### ISSUE THREAD

**Issue by ChromeFlux** [TGMP/ModularArmour#64]
Yes i have nei off when i put the recipe in, yes i had the right items, yes it recognized the recipe it just didnt allow me to press "add upgrade" and it wouldnt do anything. it just kept the items in the inventory slots.

**Comment by chbachman** [comment]
Should be fixed, I removed the old recipe, and added one without the Invis potion.

**Comment by ChromeFlux** [comment]
I am so sorry, i didnt have the potion upgrade, and that's probably why. i just thought if i could do the camouflage one i wouldnt need the potion upgrade.
