### ISSUE TITLE
How do you put in the energy upgrades? are they bugged currently?

### ISSUE THREAD

**Issue by ChromeFlux** [TGMP/ModularArmour#65]
i read somewhere that you have to have the previous type of energy upgrade to get the upgraded one. when i try to put in the reinforced energy upgrade on my chestplate it doesn't work however, its like the invisibility upgrade not being able to be put in. i have the leadstone energy upgrade, i also tried to have an extra leadstone energy upgrade materials in my inv to make it and it didnt work. are they bugged? or am i missing something

**Comment by chbachman** [comment]
Try in the newest version. I fixed a lot of GUI related bugs.

**Comment by ChromeFlux** [comment]
so does that mean the sliders overlapping problem is in that version too?

**Comment by chbachman** [comment]
Yes, that is fixed.

**Comment by ChromeFlux** [comment]
Ok. So we're trying to update to version .40 and we crashed upon opening the gui for our armour pieces. what version specifically do you want us to use?

**Comment by chbachman** [comment]
Send me the crash report.

**Comment by ChromeFlux** [comment]
http://paste.feed-the-beast.com/view/42b83889

**Comment by chbachman** [comment]
Update the CoFH Core to 3.0.3

**Comment by ChromeFlux** [comment]
Unfortunately, we've moved to the infinity modpack

So i wont be able to help, or contribute. Good luck with your mod. i really would like to see a perfect version of it in the future.
